version: '3.9'
services:

  server:
    build:
      context: .
      target: nginx
    ports:
      - "8080:80"
    networks:
      - internal

  backend:
    build:
      context: .
      target: php
    ports:
      - "9000:9000"
    networks:
      - internal

  react:
    build:
      context: .
      target: react
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - internal

networks:
 internal:
    driver: bridge