version: '3.9'

services:

  database:
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gestaomercado
      POSTGRES_USER: welles
      POSTGRES_PASSWORD: 123456
    networks:
      - internal

  server:
    build:
      context: .
      target: nginx
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - internal

  backend:
    build:
      context: .
      target: php
    ports:
      - "9000:9000"
    depends_on:
      - database
      - server
    networks:
      - internal

  react:
    build:
      context: .
      target: react
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - internal

networks:
 internal:
    driver: bridge