version: '3.9'
services:

  server:
    build:
      context: .
      target: nginx
    ports:
      - "8080:80"
    networks:
      - internal

  backend:
    build:
      context: .
      target: php
    ports:
      - "9000:9000"
    networks:
      - internal

networks:
 internal:
    driver: bridge