version: '3.9'

services:
  
  server:
    build:
      context: .
      target: nginx
    volumes:
      - ./backend:/var/www/backend
      - ./frontend:/usr/src/app:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - database
      - backend
      - react
    networks:
      - internal

  database:
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gestaomercado
      POSTGRES_USER: welles
      POSTGRES_PASSWORD: 123456
    networks:
      - internal

  backend:
    build:
      context: .
      target: php
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - database
    networks:
      - internal

  react:
    build:
      context: .
      target: react
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:
    driver: bridge